=== PARMht/Web_Tech_Exps/Exp_8/students.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, department, year)>
<!ATTLIST student id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== PARMht/Web_Tech_Exps/Exp_8/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students>
  <student id="S01">
    <name>Prem Mehta</name>
    <department>CSE (AIML)</department>
    <year>Second Year</year>
  </student>
  <student id="S02">
    <name>Shiv Kumar</name>
    <department>Information Technology</department>
    <year>First Year</year>
  </student>
</students>
